var PLAYER_MAX_SPEED = 8;
var PLAYER_ACCELERATION = 0.001;
var JUMP_HEIGHT = 10;
var MAX_CATCHUP = 10;
var BLOCK_SIZE = 32;
var HALF_BLOCK = BLOCK_SIZE / 2;
var CHUNK_SIZE = 16;
var MAGIC_NUMBER = 56;
